#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use App::INIUtils;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{parse_ini} = {
    v => 1.1,
    summary => 'Parse INI using Config::IOD::INI module and show the raw result',
    description => <<'_',

Mostly only useful for developer for debugging purposes.

_
    args => {
        %App::INIUtils::args_common,
    },
    result_naked => 1,
    'cmdline.default_format' => 'json-pretty',
};
sub parse_ini {
    my %args = @_;

    my $parser = App::INIUtils::_get_cii_parser(\%args);

    $parser->read_string($args{ini})->{_parsed};
}

my $cli = Perinci::CmdLine::Any->new(
    url => '/main/parse_ini',
    pass_cmdline_object => 1,
    read_config => 0,
    read_env => 0,
);

# so help message can be more helpful
$cli->common_opts->{format}{default} = 'json-pretty';
$cli->common_opts->{naked_res}{default} = 1;

$cli->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Basic usage:

 % parse-ini /path/to/file.ini
